### ISSUE TITLE
need to remove line #66 #67 of "lsuv_init.py"

### ISSUE THREAD

**Issue by WongKinYiu** [ducha-aiki/LSUV-keras#4]
as title

**Comment by mightypirate1** [comment]
I had this too. Removing them makes the code run, but can someone confirm that it's correct to do so?

**Comment by ducha-aiki** [comment]
Since this implementation was written, there was at least one major Keras version change. It also depends on does your layer has bias or not. Could you please clarify on this?

**Comment by WongKinYiu** [comment]
becuz keras update their api
in the updated version, the function of line #66 #67 using old api are already done in line #64 #65 using new api
 
63     -             weights, biases = layer.get_weights()
     63+            weights_and_biases = layer.get_weights()
     64+            weights_and_biases[0] /= np.sqrt(variance) / np.sqrt(needed_variance)
     65+            layer.set_weights(weights_and_biases)
64 66              weights /= np.sqrt(variance) / np.sqrt(needed_variance)
65 67              layer.set_weights([weights, biases])

**Comment by boblee2000** [comment]
UnboundLocalError: local variable 'weights' referenced before assignment
I ran into this problem.
Do you guys have any idea about that?

Thanks

**Comment by boblee2000** [comment]
fixed by removing #66#76
